export OEM_PRODUCT_MANUFACTURER=PANTECH
export SKY_ANDROID_FLAGS+="-DFEATURE_AARM_RELEASE_MODE -DMODEL_SKY -DMODEL_ID=MODEL_EF34K -DBOARD_VER=AT1_TP20 -I$PWD/include -include $PWD/include/CUST_SKY.h -DFIRM_VER=\\\"S0834211\\\" -DSYS_MODEL_NAME=\\\"EF34K\\\" -DSKY_MODEL_NAME=\\\"IM-T100K\\\" -DVARIOUS_MODEL_AT1 -DNAMING_AT1"
KERNEL_DEFCONFIG=msm8660-perf_defconfig
mkdir -p ./obj/KERNEL_OBJ
#make O=./obj/KERNEL_OBJ  clean
make O=./obj/KERNEL_OBJ $KERNEL_DEFCONFIG
make O=./obj/KERNEL_OBJ  

cp -f ./obj/KERNEL_OBJ/arch/arm/boot/zImage .

